### ISSUE TITLE
Chapter 6 Preset File

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/HigurashiVitaConverter#4]
Since once RandomNumberGeneration() is fully implemented, Chapter 6 will be fully playable, here's the preset. 

[Ch6_Tsumihoroboshi.txt](https://github.com/MyLegGuy/HigurashiVitaConverter/files/4816349/Ch6_Tsumihoroboshi.txt)

Since I'm testing Chapter 7 atm, and there's that small quirk that I'm not sure how you want to handle, I'll wait until we're "done" with that Chapter to upload my preset.

**Comment by MyLegGuy** [comment]
Thank you
I'll make a new release for the converter whenever the updated engine is released.
