### ISSUE TITLE
Chapter 7 - Minagoroshi Preset

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/HigurashiVitaConverter#5]
Since the game itself is completable, and we're just trying to fix the issues in _mina_020, here's the preset.
[Ch7_Minagoroshi.txt](https://github.com/MyLegGuy/HigurashiVitaConverter/files/4834236/Ch7_Minagoroshi.txt)

**Comment by MyLegGuy** [comment]
Thank you!
