### ISSUE TITLE
07th Mod Higurashi Chapter 1 Incorrect Script Converting

### ISSUE THREAD

**Issue by slapelachie** [MyLegGuy/HigurashiVitaConverter#6]
I run into some pretty big issues when converting the scripts while having the 07th Mod's Onikakushi Voice and Graphics Patch v7.0.1 patched onto the steam version

Upon loading the game using Higurashi-Vita v3.0.2, it crashes with a lua syntax error on this line which is found in onik_op.txt
`if(GetGlobalFlag("GADVMode)==0) thenSetDrawingPointOfMessage(0",5); end`

This issue is seen in all the scripts that are converted and does not present itself in the normal steam version

**Comment by dondepre** [comment]
The same problem happen to me. Seems that every script that has the GAVMode has misplaced the ending " and it breaks the whole structure.

**Comment by MyLegGuy** [comment]
07thMod went crazy with custom engine changes and stuff in their later versions of the patch, so only the older versions are supported. Read the instructions on the wololo thread.
